### ISSUE TITLE
Freezes MacVim

### ISSUE THREAD

**Issue by jonathanewerner** [pangloss/vim-javascript#458] opened 2016-06-02 07:33 UTC
Hi!
I'm using MacVim 7.4 (compiled May 28 2016, included patch 1-1831) and commit `0f0e4a7` from this plugin.
Given this file:
```js
export const foo = {
	bar: 'baz',
};
```

Open a new line (normal mode `o` key) on the *last line* **freezes** my vim, forcing me to quit with Command-Q.
I verified that this behaviour is introduced by activating this plugin and is gone when deactivating it.

**Comment by bounceme** [comment] 2016-06-02 07:35
dev branch

**Comment by jimmyrocks** [comment] 2016-06-02 16:04
I'm having the same issue in vim on ubuntu (VIM - Vi IMproved 7.4)
I went through the debug, and it looks like there's an infinite loop being created in `function GetJavascriptIndent`

I was able to verify this issue but reverting from commit `0f0e4a7259de3cf24be0364510d9ae4c291ec917` to commit `d7f4728f830173d5894009771432d329d9098f17` both in the Master Branch.

**Comment by dylanscott** [comment] 2016-06-02 16:14
I've observed this same issue with a static property in a class. Something like

```javascript
export default class Foo
  static prop = {
  };
  // entering insert mode here hangs vim
  bar() {
  }
}
```

**Comment by bounceme** [comment] 2016-06-02 16:18
anyone who encounters this please checkout the develop branch. also we should have master updated soon

**Comment by dylanscott** [comment] 2016-06-02 16:22
I'm still observing this issue both on develop (`5962584f25d4c06650ecb4518033c1865832011f`) and bounceme-patch-1 (`26d4fbb954fa059d9e9caf419a7351df332fad8e`). Exact repro:

On the following file place your cursor on line 6 (the line with the closing `propTypes` bracket) and press `o`.

```javascript
import React, { Component, PropTypes } from 'react'

export default class WorkflowView extends Component {
  static propTypes = {
    dispatch: PropTypes.func.isRequired,
  };

  render() {
    return <noscript/>
  }
}
```

**Comment by bounceme** [comment] 2016-06-02 16:27
I can't reproduce, can you try removing all your syntax or javascript related plugins. maybe pull the latest changes from bounceme-patch-1 too

**Comment by bounceme** [comment] 2016-06-02 16:37
i'll merge my branch to develop, if it isn't fixed, i suspect a conflicting indent or syntax file

**Comment by bounceme** [comment] 2016-06-02 16:44
as soon as we can confirm this severe issue is fixed in dev, @amadeus , @davidchambers , how about pushing dev into master?apologies again for my oversight

**Comment by davidchambers** [comment] 2016-06-02 16:52
No need to apologize, @bounceme. I'm thrilled to have you working on indentation-related issues which have gone unaddressed for a long time. It's not surprising that fixing one problem introduces another, in some cases.

**Comment by bounceme** [comment] 2016-06-03 04:12
great,that is nice to hear!

**Comment by dylanscott** [comment] 2016-06-03 15:29
Just FYI I think this probably is fixed. There seems to be something weird where checking out different branches/commits in `~/.vim/bundle/vim-javascript` is not having an effect, even with a full MacVim restart. Not sure if there's some weird caching happening somewhere.

**Comment by sherdeadlock** [comment] 2016-06-04 06:27
It's fixed in develop branch. Thanks :D

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  3 2016 19:57:36)
MacOS X (unix) version
Included patches: 1-1864
Compiled by Homebrew
```

**Comment by megapctr** [comment] 2016-06-06 12:00
Just for the record, the issue is not limited to MacVim. Using `O` or `o`  to instert a line after a static property caused freezing for me. Good to know that it's been fixed already though :)

**Comment by amadeus** [comment] 2016-06-12 03:46
Closing this because I assume it has been fixed in `develop`. Please comment if not and I can re-open.

**Closed by amadeus** 2016-06-12 03:46 UTC

**Comment by pthrasher** [comment] 2016-06-13 13:31
When will develop be merged in? Should the issue stay open until it's fixed on master?

**Comment by bounceme** [comment] 2016-06-13 21:48
I want to have the fix pushed to master as soon as possible, do you think develop is stable enough? @amadeus

**Comment by amadeus** [comment] 2016-06-13 21:49
So far the ES6 stuff has been working pretty well for me. The only thing with this next version, we should almost certainly bump it to 1.1, since so much is now working and fixed in this version.

**Comment by amadeus** [comment] 2016-06-14 00:54
This is all merged into `master` now

**Comment by jonathanewerner** [comment] 2016-06-14 06:29
Awesome, thanks!
