### ISSUE TITLE
String Literal Formatting Wrong

### ISSUE THREAD

**Issue by redreceipt** [pangloss/vim-javascript#1176] opened 2019-07-09 17:04 UTC
*Requisite minimal reproducible example, formatted as plain text :*

This text doesn't format properly:

```js
  getFromIds = (ids) =>
    this.request().filterOneOf(ids.map((id) => `Id eq ${id}`));
```

Here it is in vim:

<img width="511" alt="Screen Shot 2019-07-09 at 12 54 15 PM" src="https://user-images.githubusercontent.com/2659478/60908498-04018980-a24a-11e9-9e52-5c0578c85641.png">

<hr>

#### Optional: concerning jsx.
PLEASE PLEASE PLEASE make sure you have properly
setup and are sourcing this plugin https://github.com/mxw/vim-jsx

WE DO NOT support JSX automatically, you need another plugin to add get this
functionality.

Make sure the bug still exists if you disable all other javascript plugins
except the one noted above, mxw/vim-jsx

**Comment by redreceipt** [comment] 2019-07-09 17:05
The file is called `data-source.js` but the filetype is being set to `javascript.jsx` although there is no JSX in it. Can anyone help me figure out what's going wrong?

**Comment by amadeus** [comment] 2019-07-09 20:05
This is a duplicate of: https://github.com/pangloss/vim-javascript/issues/1150

Unfortunately I haven't had time recently to look into it.

**Closed by amadeus** 2019-07-09 20:05 UTC
