### ISSUE TITLE
Generator highlighting not always working

### ISSUE THREAD

**Issue by rightaway** [pangloss/vim-javascript#271] opened 2015-06-19 08:08 UTC
In functions like `function *func(a, b) {}` the highlighting of the asterisk works fine, but not in the following 2 cases:

```
class C {
  *func() {}
}
```

```
module.exports = {
  *func() {}
}
```

**Comment by amadeus** [comment] 2016-04-24 09:36
This first example should be fixed in `develop`, the second example is a duplicate of #261

**Closed by amadeus** 2016-04-24 09:36 UTC
