### ISSUE TITLE
Comment indent wrong between braces with othree/yajs.vim installed

### ISSUE THREAD

**Issue by tweekmonster** [pangloss/vim-javascript#427] opened 2016-05-09 15:10 UTC
I'm not sure if this is an issue with [yajs](https://github.com/othree/yajs.vim) or not, but reporting here since this plugin provides the indentation.  I have `yajs` loaded before `vim-javascript` in my vimrc.

When a comment is the first line between braces:

```javascript
{
  // test
test1
test2
}
```

When a comment is not the first line between braces:

```javascript
{
  test1
    // test
  test2
}
```

In the second example, `test2` is at the correct indentation only because the preceding comment causes it to decrease.  If you decreased the indentation of the comment and reindented the `test2` line:

```javascript
{
  test1
  // test
test2
}
```

Without the braces, the comment will match the previous line's indent:

```javascript
  test
  // test
```

But, if you re-indent the comment line a second time, the indent will increase (the previous line must be indented):

```javascript
  test
    // test
```

The only difference I saw was that `yajs` changes the syntax name from `jsLineComment` to `javascriptLineComment`.

**Comment by bounceme** [comment] 2016-05-09 15:54
why use more than one syntax plugin?this is not a bug with this plugin so I will close the issue. Thank you for reporting this though as it reminds me to try and reduce the dependence on highlight groups for indentation

**Closed by bounceme** 2016-05-09 15:54 UTC

**Comment by tweekmonster** [comment] 2016-05-09 16:10
@bounceme Did you look at yajs before closing the issue?  It provides ES6+ syntax highlighting but does not provide indentation, which I still want from vim-javascript.

**Comment by bounceme** [comment] 2016-05-09 18:10
I have seen the repo before but a likely conflict occurs when you choose to use a different syntax file than the one which this indent file requires to work properly.Having more than one syntax file for the same language means things like loading order might come into play, maybe @amadeus knows more about this?

**Comment by bounceme** [comment] 2016-05-09 18:38
You could try https://github.com/gavocanov/vim-js-indent ,which is outdated and missing quite a lot of the recent improvements,
or another indent script

**Comment by bounceme** [comment] 2016-05-09 20:16
Oh and try switching to develop

**Comment by tweekmonster** [comment] 2016-05-09 20:52
> Oh and try switching to develop

That fixed the issue!  The immediate solution I found was to add this to `yajs` to match this plugin's syntax region:

```vim
syntax region javascriptLineComment start="^\s*//" end="\n" contains=@Spell,javascriptCommentTodo
```

It looked like the issue was that it was treating it as a line starting with an operator.  I guess that was fixed in develop.  You may be able to remove the syntax region that includes the leading whitespace now.

> Having more than one syntax file for the same language means things like loading order might come into play

This should never be an issue since almost all syntax scripts honor `b:current_syntax` or deliberately ignore it without overriding the existing syntax.  It's so commonly done that it's documented, and it's how `vim-javascript` is overriding the default javascript syntax.  I would think that if a syntax plugin did screw this up, it wouldn't be popular enough to have users.

**Comment by bounceme** [comment] 2016-05-09 21:20
I didn't know that about syntax values, i would have just have guessed most people would only have maybe one file overriding the default that vim has. Of course the people that have tried working with syntax files should know all of that
