### ISSUE TITLE
Invalid argument in syntax/javascript.vim 

### ISSUE THREAD

**Issue by sahilnarain** [pangloss/vim-javascript#441] opened 2016-05-25 14:51 UTC
Changes made in commit c2bc4c70140ec761fe02c6b3a9a8370a182e931f show an error while opening a javascript file with vim.

<img width="635" alt="screen shot 2016-05-25 at 2 52 12 pm" src="https://cloud.githubusercontent.com/assets/3143331/15544359/e1eddf14-2287-11e6-9959-05776a258775.png">

**Comment by davidchambers** [comment] 2016-05-25 16:38
Duplicate of #413

**Closed by davidchambers** 2016-05-25 16:38 UTC

**Comment by amadeus** [comment] 2016-05-25 16:49
@davidchambers we should probably get `develop` merged into `master` ASAP to help alleviate this issue coming up a bunch.
