### ISSUE TITLE
Regex ending in * breaks indenting in block below it

### ISSUE THREAD

**Issue by eddiezane** [pangloss/vim-javascript#324] opened 2015-11-24 19:17 UTC
It appears a regex ending in `*` breaks indenting below it in a block.

```javascript
if (true) {
  var re = /.*/;
console.log('I am broken');
console.log('Because I end in *');
}

if (true) {
  var re = /.*$/;
  console.log('I do not end in *');
  console.log('So I am fine');
}
```

Can anyone replicate or confirm?

Apologies if this was already reported.

**Comment by davidchambers** [comment] 2015-11-24 19:32
I can't reproduce the problem. Could you disable your plugins one by one to confirm vim-javascript is responsible?

**Comment by eddiezane** [comment] 2015-11-24 21:29
Reproduced it with a completely blank vimrc aside from vim-javascript.

Try running a `gg=G` on it in a buffer?

**Comment by davidchambers** [comment] 2015-11-24 22:07
> Try running a `gg=G` on it in a buffer?

Ah, now I see it! Thanks for taking the time to verify that vim-javascript is at fault.

The problem is that none of this project's current maintainers is familiar with the indentation-related code.

**Comment by amadeus** [comment] 2016-04-20 21:56
@bounceme it appears some of the fixes we have in place, do not function when `gg=G` is used. Everything works fine when you type out the examples manually however. Any ideas?

**Comment by amadeus** [comment] 2016-04-22 04:07
This issue should be fixed in `develop`, by #390

**Closed by amadeus** 2016-04-22 04:07 UTC
Labels: confirmed bug, indentation
