### ISSUE TITLE
Incorrect indentation following single-line comments

### ISSUE THREAD

**Issue by tomxtobin** [pangloss/vim-javascript#493] opened 2016-06-17 17:51 UTC
On both `master` and `develop`, a line following a single-line comment is incorrectly indented:
```javascript
function func() {
  // comment
 // new indent starts here
}

obj = {
  // comment
 // new indent starts here
}

arr = [
  // comment
 // new indent starts here
]

call(
  // comment
 // new indent starts here
)
```
But indentation between single-line comments is (usually) fine:
```javascript
function func() {
  // comment 1
  // new indent starts here
  // comment 2
}

obj = {
  // comment 1
  // new indent starts here
  // comment 2
}

arr = [
  // comment 1
  // new indent starts here
  // comment 2
]
```
But even those seem to break if your last action was deleting a line
between `// comment 1` and `// comment 2`.

Calls seem a bit wonky:
```javascript
call(
  // comment 1
    // new indent starts here
  // comment 2
)
```
And everything behaves differently if there's a non-comment line above the comments:
```javascript
function func() {
  x
  // comment 1
    // new indent starts here
  // comment 2
}


obj = {
  x
  // comment 1
    // new indent starts here
  // comment 2
}

arr = [
  x
  // comment 1
  // new indent starts here
  // comment 2
]
call(
  x
  // comment 1
  // new indent starts here
  // comment 2
)
```

**Comment by bounceme** [comment] 2016-06-17 17:53
try the newest dev update

**Comment by tomxtobin** [comment] 2016-06-17 18:11
Just tried; all the aforementioned bugs are still present.

**Comment by bounceme** [comment] 2016-06-17 18:45
i can't reproduce any of these

**Comment by tomxtobin** [comment] 2016-06-17 18:59
I just tested with `-u NONE` and only this plugin enabled, and I'm seeing some differences.

-

**Comment by tomxtobin** [comment] 2016-06-17 19:04
I just tested with `-u NONE` and only this plugin enabled, and I'm seeing some differences.

- It doesn't happen at all if `formatoptions` has `o` and `r`. I usually disable those; I virtually never want `o` or `O` to create a new comment, and rarely `<Enter>`.

- Most of the examples I gave work normally even with `o` and `r` unset from `formatoptions`, but a few of them are still indenting incorrectly.

I'm trying to track down what combination of settings and/or plugins is causing the behavior; I'll post back as soon as I figure it out.

**Comment by tomxtobin** [comment] 2016-06-17 19:46
Actually, I'm seeing it pretty reliably now with `-u NONE` and `setlocal formatoptions-=o`, with only this plugin active.

Here's what I'm doing after starting with `-u NONE`:

- I source a file with these commands:
```vim
set runtimepath=/path-to-javascript-plugin,/other-standard-runtime-paths-except-home-dir-ones
runtime! filetype.vim
runtime! ftplugin.vim
runtime! indent.vim
runtime! syntax/syntax.vim
runtime! plugin/**/*.vim
```

- I open a file with the above examples.

- I set `formatoptions-=o`, `formatoptions-=r`

**Comment by bounceme** [comment] 2016-06-17 20:13
try and comment out this line https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L19

**Comment by tomxtobin** [comment] 2016-06-17 20:22
The `indentkeys` setting? Commenting that out breaks hitting Enter (no context-sensitive indentation at all), but that's what you'd expect. `o`/`O` is still in `indentkeys`, and manually removing those has the same effect.

**Comment by bounceme** [comment] 2016-06-17 20:25
maybe the line above:formatexpr? I'm not able to test now

**Comment by tomxtobin** [comment] 2016-06-17 20:32
Found the problem:
```vim
  " indent/javascript.vim 413:419
  " If the line is empty and the previous nonblank line was a multi-line
  " comment, use that comment's indent. Deduct one char to account for the
  " space in ' */'.
  if line =~ '^\s*$' && getline(prevline) !~ '\%(\%(^\s*\/\/\|\/\*\).*\)\@<!\*\/' &&
        \ s:IsInComment(prevline, 1)
    return indent(prevline) - 1
  endif
```
That's erroneously deleting a character from the indentation in the case of a preceding single-line (`//`) comment.

**Comment by tomxtobin** [comment] 2016-06-17 20:46
Changing the above code to the following always does the right thing for me now:
```vim
  " If the line is empty and the previous nonblank line was a comment, use
  " that comment's indent.
  if line =~ '^\s*$' && s:IsInComment(prevline, 1)
    return indent(prevline)
  endif
```
I'm not sure what the "deduct one char" bit was trying to do; I'd expect a line following the close of a multi-line comment to indent to the start of the preceding `*/`. If changing the behavior here is acceptable, I can submit a PR.

**Comment by bounceme** [comment] 2016-06-17 20:55
i would wait to make a pr, my guess is something else is going on. also, i believe deducting a char is necessary when starting a new line after a multiline comment

**Comment by bounceme** [comment] 2016-06-17 22:34
```
 if line =~ '^\s*$' && getline(prevline) =~ '\%(\%(^\s*\/\/\|\/\*\).*\)\@<!\*\/' &&
        \ s:IsInComment(prevline, 1)
    return indent(prevline) - 1
  endif
```
maybe it will work with the above? my mistake if so for the incorrect condition

**Comment by bounceme** [comment] 2016-06-18 16:13
give develop another try

**Comment by iryan2** [comment] 2016-06-20 04:35
Just chiming in to let you guys know I came across this problem earlier today, and updating to the latest develop fixed the issue for me.

**Comment by amadeus** [comment] 2016-06-20 05:57
Closing this because I believe it has been fixed in `develop`. If not someone please chime in and I can re-open.

**Comment by bounceme** [comment] 2016-06-20 16:10
what settings do you use? does this happen while typing or after `=`? still am not able to reproduce

**Comment by bounceme** [comment] 2016-06-20 17:01
I see now, this is an issue with the syntax: 
```
call(
  // existing comment 1

  // opening a new line here indents to here
)
```
the third line at col 1, is incorrectly being highlighted (though there are no are there characters show it) as a comment

**Comment by amadeus** [comment] 2016-06-21 00:08
@bounceme not sure I follow. If I type this out like you have above, I get:

![example](https://dl.dropboxusercontent.com/s/74uyy8lfk7wjvso/file.js_2016-06-20_17-08-06.png?dl=0)

**Comment by bounceme** [comment] 2016-06-21 00:26
here is the only way i can reproduce, first install https://github.com/tpope/vim-scriptease
`set fo-=o` `set fo-=r`
paste this into a blank buffer:
```
call(
  // existing comment 1
  // opening a new line here indents to here
  // existing comment 2
)
```
on the third line press `o` or `O`,sometimes it seems to not happen, but if there is another indent created press `esc` then `zS` (from scriptease)

**Comment by amadeus** [comment] 2016-06-21 00:32
Still can't reproduce. I don't use scriptease, but I have something similar for getting syntax highlighting state:

```
function! SynStack()
  echo join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")'),
    \ " > ")
endfunc
nnoremap <F7> :call SynStack()<CR>
```

I get the scenario you mentioned, where if I press `O` from the third line, it's indented twice. If I press `Esc` though, the white space gets automatically removed, and the cursor i placed at the beginning of the line, and checking my highlighting context appears normal

![example](https://dl.dropboxusercontent.com/s/i6uvmn47od77kic/durp.js_2016-06-20_17-32-26.png?dl=0)

**Comment by bounceme** [comment] 2016-06-21 00:37
what echoes when I use your function is `jsparen > jscomment`

**Comment by bounceme** [comment] 2016-06-21 00:40
this then uses c-indent, try removing this paragraph:
https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L333

**Comment by bounceme** [comment] 2016-06-21 02:24
<img width="421" alt="screen shot 2016-06-20 at 7 22 52 pm" src="https://cloud.githubusercontent.com/assets/9332107/16216068/935cf6ce-371c-11e6-89c4-707526c39f0d.png">

**Comment by amadeus** [comment] 2016-06-21 03:15
@bounceme what version of Vim/MacVim do you have?

I've seen this sorta thing before, although usually if you type something or what a second, it fixes itself.

**Comment by bounceme** [comment] 2016-06-21 03:29
vim 7.4.1941

**Comment by bounceme** [comment] 2016-06-21 07:22
I can do something to fix the indenting at least, if this is just a general syntax problem

**Comment by amadeus** [comment] 2016-06-21 18:06
All the `jsComment` stuff is super legacy. I can take a stab at modernizing it a bit, and see if that fixes things?

**Comment by bounceme** [comment] 2016-06-21 18:13
that'd be great! thanks

**Comment by amadeus** [comment] 2016-06-21 18:38
@bounceme with what I just merged into `develop`, can this issue be marked as solved?

**Comment by bounceme** [comment] 2016-06-21 18:52
yes, this troublesome issue is gone haha

**Closed** 2016-06-21 18:52 UTC
