### ISSUE TITLE
incorrect indentation for after chained promise calls

### ISSUE THREAD

**Issue by wellsjo** [pangloss/vim-javascript#451] opened 2016-05-30 16:28 UTC
Ever since 3208fc5, indenting after chained promise calls doesn't work correctly (everything shifts over a tab).  Example:

```javascript
someFunction()
.then(_ => console.log('hello'))
.then(_ => console.log('there'));

  // everything below here gets shifted over a tab >>

  /**
   * Comments
   */
  anotherFunction() {
   
  }

```

**Comment by bounceme** [comment] 2016-05-30 16:38
fixed in my pr

**Comment by bounceme** [comment] 2016-05-30 16:41
oh, not yet actually

**Comment by bounceme** [comment] 2016-05-30 18:14
fixed in develop

**Comment by wellsjo** [comment] 2016-05-30 18:17
awesome :-D

**Comment by wellsjo** [comment] 2016-05-31 01:19
@bounceme I found another edge case. if there is a line between function calls, they are incorrectly shifted back 

Example:
```javascript
foo
  .bar()

// comment
.baz();
```

**Comment by bounceme** [comment] 2016-05-31 04:06
i can't reproduce, though i'm working with some local changes right now

**Comment by bounceme** [comment] 2016-05-31 05:16
maybe look for conflicting scripts?

**Comment by wellsjo** [comment] 2016-05-31 16:15
what version of vim-javascript should I use to test?

**Comment by bounceme** [comment] 2016-05-31 21:30
dev branch, or something is wrong with your setup possibly?

**Comment by wellsjo** [comment] 2016-06-02 00:37
Does this break for you?
```javascript
func
  .anotherfunc()

/**
 *
 */
  function foo() {

  }
```

**Comment by bounceme** [comment] 2016-06-02 01:22
no,function foo is aligned with func

**Comment by wellsjo** [comment] 2016-06-02 13:39
must be my setup then. dang, do you have tips on how to debug this? it's really hard!

**Comment by zamN** [comment] 2016-06-05 20:49
@wellsjo same exact setups? Same `.bashrc`'s, `.vimrc`'s, vim plugins, etc? Do you use a plugin manager for vim? If so I'd say nuke your vim plugin directory on Ubuntu and then try re-installing all your plugins. Do the same for Mac, but backup your 'working' `.vim` directory first. Doing this will help you isolate what is possibly conflicting.

**Closed** 2016-06-11 23:12 UTC
