### ISSUE TITLE
Indentation problem with && and || operators

### ISSUE THREAD

**Issue by sassanh** [pangloss/vim-javascript#557] opened 2016-07-19 18:38 UTC
Thanks for this great extension.
I have a problem, it indents like this:
```
const dialog = (
    location.hash.dialog ||
        location.query.dialog ||
        location.pathname.substr(1)
);
```

while I expect it to indent it like this:
```
const dialog = (
    location.hash.dialog ||
    location.query.dialog ||
    location.pathname.substr(1)
);
```
Is it a bug or should I set a variable to avoid it?

**Comment by bounceme** [comment] 2016-07-19 19:58
how about on develop?

**Comment by amadeus** [comment] 2016-07-19 20:02
This appears fixed on `develop`

**Comment by sassanh** [comment] 2016-07-19 20:19
Yes it's fixed on `develop` thanks.

**Comment by bounceme** [comment] 2016-07-20 05:23
actually though,this may be the most accurate behavior, there shouldn't be additional indent caused by commas since those divide the calling arguments, which is where special consideration is made (try and replace those operators with commas, on master) however other operators make a continuation, though separate from this

**Closed** 2016-07-20 05:26 UTC
