### ISSUE TITLE
"catch" is always highlighted as a keyword, independent of context

### ISSUE THREAD

**Issue by rolodato** [pangloss/vim-javascript#290] opened 2015-08-26 19:22 UTC
For example, this code:

```js
foo().then().catch();
try {} catch(e) {}
```

is rendered like this:

![image](https://cloud.githubusercontent.com/assets/829698/9503623/7eafbb2a-4c0e-11e5-81b6-a037c039e5f3.png)

This is handled correctly by WebStorm, for example:

![image](https://cloud.githubusercontent.com/assets/829698/9503631/94272de4-4c0e-11e5-9953-f02f82b611bd.png)

**Comment by davidchambers** [comment] 2015-08-27 02:05
This is somewhat related to #180.

**Comment by rolodato** [comment] 2015-08-27 02:43
Thanks for pointing that out, I had searched the issues for something like this but didn't find it.

I have no clue how vim plugins or vim's syntax highlighting work in general but if there's something I can do in helping with a fix, please let me know.

**Comment by amadeus** [comment] 2016-04-24 10:45
Since this is a duplicate of #180, closing.

**Closed by amadeus** 2016-04-24 10:45 UTC
