### ISSUE TITLE
Does not work together with rainbow parantheses for me

### ISSUE THREAD

**Issue by v76591wC** [pangloss/vim-javascript#184] opened 2014-04-16 07:16 UTC
When I use vim-javascript together with kien/rainbow_parentheses.vim matching parentheses do not have different colors. This works however for files that are not javascript files. Disabling vim-javascript makes the parentheses have different colors so I wonder if anyone has an idea how to fix this.

**Comment by krzkrzkrz** [comment] 2015-08-14 18:56
One year later. Seeing this as well... guess no updates since then?

**Comment by lookforit** [comment] 2015-11-23 03:37
Seeing the same issue...
Looking for a perfect fix version.

**Comment by ognivo** [comment] 2016-02-10 11:28
Same issue, subscribed.

**Comment by ctataryn** [comment] 2016-06-03 16:33
Same issue for me, rainbowparens breaks on javascript files when I'm using `vim-javascript`. Unfortunately @caleb's fix didn't work for me :cry:

**Comment by amadeus** [comment] 2016-06-12 03:44
Unfortunately the way our syntax file works, I am am almost positive it is impossible to support Rainbow parentheses.

It's probably even worse now that we have special support for ES6/7 functionality. Going to close this, but will consider re-opening if someone can figure out how to get it working, although I doubt it.

**Closed by amadeus** 2016-06-12 03:44 UTC

**Comment by laughinghan** [comment] 2016-06-29 20:12
@caleb's workaround worked for me; I also improved on it so that not just the function body braces are correctly highlighted, but also the function parameter parens are:

```
autocmd FileType javascript syntax clear jsFuncBlock jsFuncArgs
```

**Comment by laughinghan** [comment] 2016-06-29 20:35
> Fixing this could be a slippery slope, since it's a third party plugin that has different interpretations for how to approach matching the syntax.

I totally appreciate this, but the thing is, `vim-javascript` appears to be the only language highlighter with this problem. This suggests that to the extent that a rough consensus interpretation exists for how to approach matching the syntax, the various rainbow paren highlighters mentioned are all conforming to the consensus, as are the other language highlighters, whereas `vim-javascript` isn't.

> personally I am not really a fan of actually breaking some of the special features we offer to support this

Which features break? If it's just code folding or some other optional feature that a large segment of users don't care about (including myself and others in this thread), there's potentially a workable compromise where we can set a flag and `vim-javascript` will break code folding or whatever to allow rainbow parens to work. How would you feel about that?

**Comment by amadeus** [comment] 2016-06-29 20:40
Code folding is the least of it. It has to do with code detection accuracy, and the complications that have arisen out of new JS functionality added in ES6 and ES7. Basically the problem arises because we have very specialized detection of syntax regions, and because of this, we create a variety of scopes to actually properly map valid JS where it's appropriate. To my knowledge, most other syntax files aren't as precise as ours.

You're free to not use this plugin. Vim has a built in syntax file for Javascript, you can just use that and get your rainbow parenthesis functionality.

**Comment by laughinghan** [comment] 2016-06-29 20:40
In #85, @amadeus noted about the workaround @caleb and I are using:

> @laughinghan that command will pretty much break most of the syntax highlighting if you do that, btw.

What kinds of things should break? Looks fine to me:
<img width="277" alt="screen shot 2016-06-29 at 16 29 18" src="https://cloud.githubusercontent.com/assets/225809/16467727/9ce4c310-3e16-11e6-8dc0-a42c408f3db6.png">

**Comment by amadeus** [comment] 2016-06-29 20:46
If I open a file and run `:syntax clear jsFuncBlock jsFuncArgs`

I go from this:

![good example](https://dl.dropboxusercontent.com/s/i8t7n3o01ejl80s/Desktopvim-javascript_2016-06-29_13-45-06.png?dl=0)

to this:

![bad example](https://dl.dropboxusercontent.com/s/w8swaygpf6395v4/Desktopvim-javascript_2016-06-29_13-45-20.png?dl=0)

**Comment by laughinghan** [comment] 2016-06-29 20:57
Ah, thanks for the clarification. (By the way, do you have a special tool for the window-with-shadow-on-white-background screenshots? Looks dope!)

I think the main reason I use `vim-javascript` instead of the built-in syntax file is the vastly improved indentation support, which doesn't appear to be broken by the `syntax clear ...` "workaround", and I don't use much ES6/7 (yet).

I certainly don't have the expertise to propose a more surgical fix. For posterity, I just noticed that [semantic-highlight.vim](https://github.com/jaxbot/semantic-highlight.vim) has an identical problem to rainbow parens, which is also fixed by the "workaround".

**Comment by amadeus** [comment] 2016-06-30 02:26
I use [Monosnap](https://monosnap.com/welcome) for screenshots usually, although I think there's a built in method in OSX to take a similar window only type screenshot.

**Comment by amadeus** [comment] 2016-06-30 02:27
Have you tried pinging the guy who maintains rainbow parens and see if he has a way to fix it on his end? I still don't think it's possible without re-doing our syntax file completely, but maybe he has an insight.

**Comment by bounceme** [comment] 2016-07-04 04:16
can we do anything like https://github.com/neovim/neovim/blob/8849c209cc0ae94d60a814b55397d80c2c16a185/runtime/syntax/lisp.vim#L45-L59 with this syntax file?

**Comment by amadeus** [comment] 2016-07-04 04:21
Because we have so many different types of regions, it would grow exponentially for every nested region

**Comment by bounceme** [comment] 2016-07-04 04:26
oh, good too know

**Comment by laughinghan** [comment] 2016-11-05 07:58
FYI as of latest `master` (997c2b12f5fffedd3a787b8840dfe710b2e6d3f9), the workaround is no longer necessary (in fact, the workaround breaks now), vim-javascript and Rainbow Parentheses and semantic-highlight.vim all seem to work together out of the box now 🎉 🎊 🎈 ✨

**Comment by bounceme** [comment] 2016-11-07 00:40
I have to wonder how anything changed since then

**Comment by flipjs** [comment] 2016-11-07 08:51
@laughinghan I can confirm, it works for me too. I completely removed the work-around (jsfuncblock) in my vimrc. Thanks!

**Comment by bounceme** [comment] 2016-11-10 20:02
Does this work with only vim-javascript and rainbow-parens active (no other syntax/highlight plugins)?

**Comment by laughinghan** [comment] 2016-11-14 23:43
Well in addition to rainbow parens, it works for me with semantic-highlight.vim too (as I mentioned), but I have not tried with anything else. I would assume that if it works with both of those, which were worked-around the same way, it'll work with other stuff too.

**Comment by bounceme** [comment] 2016-11-15 05:41
and it now works, even inside of funcblock? what about just using one or the other of those plugins? if you do test that, post your findings, i'm pretty curious

**Comment by laughinghan** [comment] 2016-11-15 08:25
Assuming that:
```js
function f (arg1, arg2) {
  // this is funcblock
}
```
Then yeah, just jaxbot/semantic-highlight.vim works:
<img width="555" alt="screen shot 2016-11-15 at 00 15 00" src="https://cloud.githubusercontent.com/assets/225809/20298062/c85f2caa-aac8-11e6-87a7-c5ea578e1235.png">

As does just eapache/rainbow_parentheses.vim:
<img width="556" alt="screen shot 2016-11-15 at 00 22 44" src="https://cloud.githubusercontent.com/assets/225809/20298261/ba5a1380-aac9-11e6-8708-6ca7dc593723.png">

My setup should be pretty easy to reproduce, in the homedir of a new user just git clone my dotfiles and run `install.sh`: https://github.com/laughinghan/dotfiles

**Comment by laughinghan** [comment] 2016-11-15 08:29
I guess the function argument parens aren't rainbow-colored, which is strictly speaking a bug:
```js
function config -->(<-- currentOptions, newOptions -->)<-- {
  ...
}
```
but other than the fancy new argument destructuring syntax, you can't have nested parens there anyway.

**Comment by laughinghan** [comment] 2016-11-18 00:58
I'm sorry, I'm horribly mistaken!!!

It turns out that `syntax clear jsFuncBlock` was breaking `vim-javascript`'s highlighting of certain ES6 (specifically, template strings ``` `Missing configuration field ${field}` ``` inside a funcblock), **just as y'all have warned me**. I was in the middle of something so I just went ahead and installed `vim-es6`, which from what I can tell has completely overridden everything about `vim-javascript`, causing `syntax clear jsFuncBlock` to error but also causing rainbow parens and semantic-highlight.vim to work without any such workarounds.

In fact, the polar opposite of what I initially reported is true. If I remove `vim-es6` but leave the upgraded `vim-javascript`, then even with the workaround semantic highlighting and rainbow parens are broken; in other words, upgrading `vim-javascript` breaks the hacky workaround.

I've removed `vim-javascript` from my setup and switched to `vim-es6` for now. Sorry for the confusion!

(Also, now I'm really confused how @flipjs reported repro-ing my mistake?!)

**Comment by laughinghan** [comment] 2016-11-18 01:32
Honestly I'm pretty confused/curious why `vim-es6` _doesn't_ have this problem (of breaking rainbow parens and semantic highlighting in funcblocks). Both `vim-javascript` and [YAJS](https://github.com/othree/yajs.vim) have this problem.

**Comment by amadeus** [comment] 2016-11-20 23:35
If you have a way to inspect syntax highlighting regions in vim, then going through a JS file and inspecting those regions with our file vs the others will show a lot more syntax granularity, accuracy and scope vs the other plugins.

I have a sneaky suspicion Rainbow parens break whenever we assign `matchgroups` to a region, which is a very important and powerful way for us to define regions.

**Comment by bounceme** [comment] 2016-11-21 00:11
```
	In a start or end pattern that is highlighted with "matchgroup" the
	contained items of the region are not used.  This can be used to avoid
	that a contained item matches in the start or end pattern match.  When
	using "transparent", this does not apply to a start or end pattern
	match that is highlighted with "matchgroup".

```
what about "transparent" ?

**Comment by bounceme** [comment] 2016-11-21 02:42
i just tried `%s/\(matchgroup\S*\)/transparent \1/g` but nothing changed

**Comment by bounceme** [comment] 2017-02-01 19:05
https://github.com/bounceme/poppy.vim is similar, and works with any syntax file

**Comment by uncledu** [comment] 2018-07-11 08:02
same issue, mark

**Comment by bangarangler** [comment] 2020-03-03 14:25
Still no solution for this?  I understand it seems to be a rainbow specific issue. but would love to have rainbow parens working with syntax highlighting as well instead of a ton of white {[( all over the place.  Thanks all ; ) appreciate the hard work
