### ISSUE TITLE
Object Destructuring Defaults Shows Error

### ISSUE THREAD

**Issue by redreceipt** [pangloss/vim-javascript#1152] opened 2018-11-26 14:36 UTC
*Requisite minimal reproducible example, formatted as plain text :*

When destructuring objects and using defaults, I'm getting the closing bracket highlighted. I believe this is correct syntax as it is not throwing linter errors but any help would be appreciated.

![screen shot 2018-11-26 at 9 31 11 am](https://user-images.githubusercontent.com/2659478/49020483-8c6d6700-f15e-11e8-9321-9832004db321.png)

**Comment by redreceipt** [comment] 2019-07-09 17:25
Any word on this issue?

**Comment by amadeus** [comment] 2019-07-09 20:00
This is actually a duplicate of this issue:

https://github.com/pangloss/vim-javascript/issues/1092

It's unfortunately very hard, maybe even impossible to fix.

**Closed by amadeus** 2019-07-09 20:00 UTC
