### ISSUE TITLE
[flow] syntax issue for maybe types within parenthesis 

### ISSUE THREAD

**Issue by peey** [pangloss/vim-javascript#983] opened 2017-06-15 19:03 UTC
I'm having having syntax issues with the following:

```js
function parseFor(init: ?(N.VariableDeclaration | N.Expression)): N.ForStatement {
  return "nothing special";
}
```
vim highlights the second closing bracket as a syntax error

I've reduced this to the following:

```js
function parseFor(init: ?(N.Expression)): N.ForStatement {
  return "nothing special";
}
```

which reproduces the same error (but isn't very useful for demonstration of where this might be used)

And the following works fine without any errors: (checked for sanity testing)
```js
function parseFor(init: ?N.Expression): N.ForStatement {
  return "nothing special";
}

// or without the maybe type
function parseFor2(init: (N.VariableDeclaration | N.Expression)): N.ForStatement {
  return "nothing special";
}
```

**Comment by peey** [comment] 2017-06-15 19:05
Is this related to https://github.com/pangloss/vim-javascript/issues/901 ?

**Comment by bounceme** [comment] 2017-06-20 17:57
it's a problem with the parenthesized maybe type

**Comment by dcosson** [comment] 2017-06-22 18:00
I don't think this is the same as #901 but could be related. In that issue, syntax checking breaks later in the file after a certain character, in this case the closing paren is highlighted red and later things in the file syntax highlight ok. I constantly run into both issues, here is a simple case that reproduces this one:

![screen shot 2017-06-22 at 10 58 32 am](https://user-images.githubusercontent.com/708904/27448486-cc589c6a-5739-11e7-9761-6b38082b7628.png)

The combination of the last arg having an optional type and the function having a typed return value seems to be what breaks the highlighting.  In other permutations (no typed return value, or a non-optional arg type following the optional one) there is no problem. And as you can see, the line after the error is highlighted fine.

**Comment by bounceme** [comment] 2017-06-22 18:43
we need people contributing to the flow stuff, or , facebook could provide support themselves. they seem to want nuclide to remain first class above all else though

**Comment by dcosson** [comment] 2017-06-22 20:49
I took a brief look at it but I'm brand new to vim syntax so not fully following everything.  From what I can tell, it looks like at least one part of the problem is that if an arrow function specifies any return type, the parens get parsed as jsParens instead of jsFuncParens. From what i understand of the syntax it looks like it should be working though, haven't found the bug yet.

**Comment by amadeus** [comment] 2017-06-26 07:22
I've recently created a branch with some flow fixes, if you could do me a solid and test it: https://github.com/pangloss/vim-javascript/pull/991

**Closed** 2017-07-12 20:30 UTC
Labels: flow
