### ISSUE TITLE
recent changes broke general un-indentation of close-bracket

### ISSUE THREAD

**Issue by unphased** [pangloss/vim-javascript#754] opened 2016-12-07 06:41 UTC
inside a function scope if you use vim-surround to close a bracket or type it out, it does not reindent anymore. 

It's particularly aggravating because it infects the `=` reindent behavior too, thus breaking all javascript autoindent attempts by leaving the close bracket indented. 

I checked with git locally to find this change happened in the past week, because I tested the Nov 30 commit and it was fine. I'll look into it a bit more tomorrow.

**Comment by bounceme** [comment] 2016-12-07 06:45
what is your indentkeys setting?

**Comment by unphased** [comment] 2016-12-07 06:46
indentkeys=0{,0},:,0#,!^F,o,O,e,0],0)

**Comment by bounceme** [comment] 2016-12-07 06:47
reproduce steps ? i have surround also

**Comment by unphased** [comment] 2016-12-07 06:48
- any time you type `}`, it fails to de-dent it
- any time you take any nontrivial amount of code and visual-select it and hit `=` to auto-indent it, it fails to de-dent the `}`

**Comment by bounceme** [comment] 2016-12-07 06:51
can you list any packages related to javascript

**Comment by unphased** [comment] 2016-12-07 06:51
not really anything specific. I did a bisect and this is the commit that introduced the problem for me. 039c611

**Comment by bounceme** [comment] 2016-12-07 06:53
nothing in that commit would cause that

**Comment by unphased** [comment] 2016-12-07 06:54
well.... 

what about how the call to `cursor` got moved around.

grasping at straws.

**Comment by unphased** [comment] 2016-12-07 06:55
i can make a screencast reproduction when im on my mac later.

**Comment by unphased** [comment] 2016-12-07 06:58
It actually doesnt chain-break all indentation. It basically changes the "style" so that the close-brace is indented, once we move past that line the next line becomes de-dented. 

Like this is how it "corrects" things to, after that particular change:

    this is some code {
        indented code
        } // still indented close bracket!!!
    more continued code

**Comment by bounceme** [comment] 2016-12-07 06:58
I would go through your vimrc and disable anything filetype/syntax/indent related except for what comes from this repo. the problem would otherwise affect other people as well ( I can't reproduce )

**Comment by unphased** [comment] 2016-12-07 06:59
OK I will try that next. Thanks.

**Comment by unphased** [comment] 2016-12-07 18:37
My manual vimrc bisecting led me to this...

    filetype plugin indent on

I do believe that if you do not have this, then the custom javascript syntax isn't even being used... So i'm not sure what's going on on your end, but I would really love it if 039c611 got reverted

**Comment by bounceme** [comment] 2016-12-07 18:43
try `:echom &indentkeys` and `:echom &indentexpr` and report the result

**Comment by bounceme** [comment] 2016-12-07 18:51
also disable any concealing

**Comment by bounceme** [comment] 2016-12-07 18:55
and if you are using tabs, change to spaces. I am now out of ideas

**Comment by unphased** [comment] 2016-12-07 19:00
`:echom &indentkeys` and `:echom &indentexpr` are, respectively:
`0{,0},:,0#,!^F,o,O,e,0],0)` (it's like we saw earlier)
`GetJavascriptIndent()`

If I take out `filetype plugin indent on` from my vimrc, I see for them: 

`0{,0},:,0#,!^F,o,O,e`
`` (empty)

**Comment by bounceme** [comment] 2016-12-07 19:03
I'll make a commit now, if it doesn't change then it atleast proves 039c611  was harmless

**Comment by unphased** [comment] 2016-12-07 19:05
Well, I don't really need you to make changes to this repo yet, I can easily test the reverting of a commit via git myself. But I appreciate that you're helping me on this!

Now, when I set my vimrc to the most basic barebones setup: 

```
set nocompatible
set encoding=utf-8
set showcmd

set autoindent
set smartindent

filetype off " Vundle needs this

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

Plugin 'pangloss/vim-javascript'

filetype plugin indent on
```

The bad behavior is also reproduced. I also cleared out my own `.vim/syntax/javascript` script. So this is pretty conclusive unless i'm still missing something else to reset.

**Comment by bounceme** [comment] 2016-12-07 19:06
smartindent?

**Comment by bounceme** [comment] 2016-12-07 19:08
and try bypassing vundle and setting rtp to this repos folder

**Comment by unphased** [comment] 2016-12-07 19:12
smartindent doesnt seem to affect anything. 

But changing the rtp did the trick. 

So what does that mean?!?!

**Comment by bounceme** [comment] 2016-12-07 19:12
vundle is not being used correctly

**Comment by unphased** [comment] 2016-12-07 19:15
Yeah, its from vundle instructions from almost 4 years ago. So I updated to use `call vundle#begin()` and it seems ok now...

This is really weird though and doesnt explain the root cause of the issue.

**Comment by bounceme** [comment] 2016-12-07 19:16
what issue remains?

**Comment by unphased** [comment] 2016-12-07 19:19
Well, I modernized my vundle setup and the same issue remains, so i'm back to bisecting again

**Comment by unphased** [comment] 2016-12-07 19:23
Here's my now minimal (should be compliant) vundle-using config: 

```
set nocompatible
set encoding=utf-8
set showcmd
set autoindent

filetype off " Vundle needs this

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'pangloss/vim-javascript'
call vundle#end()

filetype plugin indent on
```

Still reproduces the bad `indentkeys`

**Comment by bounceme** [comment] 2016-12-07 19:24
this should be moved to the vundle repo

actually, ditch vundle if you can. Pathogen is the recommendation on the readme, but vim-plug is also simple.

**Comment by unphased** [comment] 2016-12-07 19:24
Also, I do not know what `indentkeys` controls. 

I'll keep trying stuff as long as I have time, but so far it seems like your latest commit on master unbreaks it even with the "wrong" `indentkeys`.

**Comment by bounceme** [comment] 2016-12-07 19:27
something is _incorrect_ with your setup. you should figure that out, stop using vundle and switch to something that doesnt require hacks like `filetype off`

**Comment by unphased** [comment] 2016-12-07 19:27
alright thanks. 

Also i think `indentkeys` is a red herring. 

`Last set from ~/.vim/bundle/vim-javascript/indent/javascript.vim`

**Comment by unphased** [comment] 2016-12-07 19:47
I can confirm with vim-plug the same behavior i saw with vundle. this is the config

```
set nocompatible
set encoding=utf-8
set showcmd
set autoindent
filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'pangloss/vim-javascript'
call plug#end()
```

**Comment by bounceme** [comment] 2016-12-07 19:59
If it's fixed on master can this be closed?

**Comment by unphased** [comment] 2016-12-07 20:00
Yes i'm leaning towards closing it, but it seems like something is still afoot, because you indicate that at no point in time could you reproduce the problem, and for me whenever I'm on the problematic commits I get the problem.

**Comment by bounceme** [comment] 2016-12-07 20:03
https://github.com/pangloss/vim-javascript/commit/039c611e1a6af83e3ce34283630a9d811fc97981#diff-564c1f6e79518959361f7ad8a86f5792R204 could have been the problem. that was more a clever shorthand, but maybe `indent()` is dependent on something like byte length differences in tab/space?

**Comment by bounceme** [comment] 2016-12-07 20:05
anyway, substitute is foolproof

**Closed** 2016-12-07 21:27 UTC

**Comment by bounceme** [comment] 2016-12-07 23:16
for closure: accessing a substring uses byte count rather than column count which indent returns

**Comment by unphased** [comment] 2016-12-07 23:18
So you are saying that we should expect that "broken code" to break only for tab indented files.

**Comment by bounceme** [comment] 2016-12-07 23:20
yea
