### ISSUE TITLE
Invalid syntax highlighting for tagged template strings

### ISSUE THREAD

**Issue by chocolateboy** [pangloss/vim-javascript#242] opened 2015-02-15 21:09 UTC
vim-javascript: 0.10.0 (e9709a9fb29ed0739eb244b5e70211c1ab647535)
vim: 7.4.52
OS: Linux (Ubuntu 14.04.1)

Syntax highlighting doesn't seem to be handling tagged template strings correctly e.g.:

```javascript
foo(test`foo`, "bar", baz);
```

\- highlights everything up to the closing backtick correctly (i.e. the tag is green and the template and its delimiters are red), but everything after that is green (to the end of the line). This also breaks highlighting for other elements e.g.:

```javascript
it('highlights tagged templates', function () {
    assert.equal(test`foo`, 'foo');
}); // <- closing curly bracket highlighted in red
```

\- highlights the closing curly bracket as an error (red).

**Comment by goatslacker** [comment] 2015-02-15 21:27
A quick solution would be to remove the `contains=jsTemplateStrings` for `jsTaggedTemplate` this would however highlight the tag + the string as a `StorageClass`.

**Comment by amadeus** [comment] 2015-02-16 00:47
Actually, I think all we need is `keepend` added to the `jsTaggedTemplate` region

**Comment by amadeus** [comment] 2015-02-16 00:50
And I don't really use anything ES6 these days, but I believe the end matcher on `jsTaggedTemplate` is wrong. Aren't these template strings supposed to be able to span multiple lines? Currently the ending regex is 

```
+`\|$+
```

 which ends the template string with a linebreak, which I think is incorrect?

**Comment by goatslacker** [comment] 2015-02-16 01:40
We can remove the $ and add keepend.

**Comment by raine** [comment] 2015-09-05 00:13
Broken as such:

<img width="201" alt="screen shot 2015-09-05 at 3 13 31" src="https://cloud.githubusercontent.com/assets/11027/9696622/1b9280e8-537c-11e5-9211-9ebd1dddce79.png">

**Comment by epaminond** [comment] 2016-06-25 21:20
It seems I have the same issue on neovim.

**Comment by amadeus** [comment] 2016-06-25 21:26
@epaminond there appear to be 2 separate issues in here. Can you specify which issue or post a code snippet?

**Comment by epaminond** [comment] 2016-06-25 21:30
@amadeus, syntax highlighting for template strings doesn't take into account closing back quote:
![image](https://cloud.githubusercontent.com/assets/1932290/16359224/f2407c1c-3b34-11e6-9d49-5050815c4bf3.png)

**Comment by amadeus** [comment] 2016-06-25 21:37
Thanks, @epaminond I'll take a look into this shortly. In the meantime could you paste that snippet as text in a comment so I can easily test it?

**Comment by epaminond** [comment] 2016-06-25 21:39
Thanks. Here's a snippet:
```
<div className={`caption ${this.isInPast(day, day) ? 'progress' : ''}`}>
  {day.format('dd - MMM DD')}
</div>
```

**Comment by amadeus** [comment] 2016-06-26 00:01
@epaminond on my initial tests in the `develop` branch, this issue does not appear to exist. How up to date is your plugin?

**Comment by amadeus** [comment] 2016-06-26 03:47
Closing this for now since I cannot reproduce the issue with the latest version of this project.

**Closed by amadeus** 2016-06-26 03:47 UTC

**Comment by epaminond** [comment] 2016-06-26 17:03
@amadeus, I'm using Vundle so I believe it's latest version available.

**Comment by amadeus** [comment] 2016-06-26 20:33
@epaminond when was the last time you updated your bundles though? You have to do that manually via `:PluginInstall(!)` (I think that's the command, I don't use Vundle.

**Comment by epaminond** [comment] 2016-06-26 20:41
@amadeus, I know, I did that.

**Comment by bounceme** [comment] 2016-06-26 21:32
template strings for what, some html tempting system or jsx? if so you'll need the vim jsx plugin or something like it since that isn't valid js, at least within a regular js file

**Comment by amadeus** [comment] 2016-06-26 21:33
@bounceme good point. I assumed he has the jsx plugin installed. I do, so everything works as expected.

**Comment by amadeus** [comment] 2016-06-26 22:59
Upon further tests, @epaminond I can see the issue is that you are editing in JSX syntax, but either you do not have the proper JSX plugin installed, or the filetype for that particular file is not set to `javascript.jsx`.

**Comment by epaminond** [comment] 2016-06-27 05:47
@amadeus, this worked for me, thanks a lot! :)

**Comment by DoWhileGeek** [comment] 2016-12-05 20:56
Just to add for future people, right at the top of the [usage section](https://github.com/mxw/vim-jsx#usage) in `vim-jsx` is the instruction you need to use it on regular `.js` files.

**Comment by tamer1an** [comment] 2017-03-01 21:26
![devtool](https://cloud.githubusercontent.com/assets/956869/23482043/f0184976-fecd-11e6-823e-dc74b7e2d9b1.png)

 56.0.2924.87 (64-bit)

**Comment by amadeus** [comment] 2017-03-01 21:40
@tamer1an can you please copy paste a snippet that breaks as well? The screenshot is helpful, but not for reproducing.

**Comment by sepehr500** [comment] 2017-04-11 15:58
I am having the same issue. Template literals break the syntax just as shown above.

**Comment by sepehr500** [comment] 2017-04-11 16:03
I am having the same issue as the person above as well and I do have `let g:jsx_ext_required = 0` enabled.

**Comment by amadeus** [comment] 2017-04-12 16:36
Again, please provide a snippet I can copy and paste that shows the issue.

**Comment by lion19** [comment] 2017-04-21 17:47
@amadeus I believe this is a representative sample: 
```
<div> {`${anything here}`}
  makes anything following format in the color reserved for strings
</div>
```

**Comment by amadeus** [comment] 2017-04-21 18:22
![example](https://dl.dropboxusercontent.com/s/aiea5m5elb8kf6s/_2017-04-21_11-21-28.png?dl=0)

Looks fine to me. Also this is a JSX snippet, not a javascript snippet. You probably aren't sourcing the JSX plugin

**Comment by dcosson** [comment] 2017-05-12 21:25
In case it helps anyone - I was running into a very similar error with backticks breaking later formatting and closing braces getting highlighted red. I had the vim-jsx plugin installed/configured correctly but the issue was flow. If you have any flow annotations in your code, make sure to add this to your config:

```
 let g:javascript_plugin_flow = 1
```

**Comment by jeromecovington** [comment] 2017-11-10 19:19
For me, the issue was not parsing jsx syntax in js files, so I added the following to my `.vimrc.local` file:
```
let g:jsx_ext_required = 0
```

Now, backticks and subsequent jsx tags are properly highlighted.
